apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "thischart.fullname" . }}
  labels:
    app: {{ template "thischart.name" . }}
    chart: {{ template "thischart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "thischart.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "thischart.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: UBIRCH_KC_URL
              value: {{ .Values.adminUi.keyCloak.url }}
            - name: UBIRCH_TR_KC_REALM
              value: {{ .Values.adminUi.keyCloak.testRealm.realmName }}
            - name: UBIRCH_KC_CLIENTID
              value: {{ .Values.adminUi.keyCloak.clientId }}
            - name: UBIRCH_TR_KC_CRED_SECRET
              value: {{ .Values.adminUi.keyCloak.testRealm.secret }}
            - name: UBIRCH_TR_ENV_SERVURL
              value: {{ .Values.adminUi.env.serverUrl }}
            - name: UBIRCH_TR_API_PREF
              value: {{ .Values.adminUi.env.apiPrefix }}
            - name: UBIRCH_TR_CLIENT_NAME
              value: {{ .Values.adminUi.keyCloak.testRealm.clientName }}
            - name: UBIRCH_TR_DEFAULT_DEVICE_TYPE
              value: {{ .Values.adminUi.keyCloak.testRealm.defaultDeviceType }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
